apiVersion: v1
kind: Config
clusters:
  # The name of the service
  - name: kubernetes-github-authn
    cluster:
      server: http://localhost:3000/authenticate
users:
  # The api configuration for the webhook
  - name: authn-apiserver
    user:
      token: secret
contexts:
  - name: webhook
    context:
      cluster: kubernetes-github-authn
      user: authn-apiserver
current-context: webhook
